### ISSUE TITLE
Fastlogin don't work on 1.18 bungeecord

### ISSUE THREAD

**Issue by elmaslarry** [games647/FastLogin#664]
### What happened?

The plugin don't work on 1.18 bungeecord

### What did you expect?

that work on 1.18

### Steps to reproduce

install the latest 1.18 bungeecord and fastlogin 

### Server log

```shell
[12:02:48 WARN]: Exception encountered when loading plugin: FastLogin
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
        at com.github.games647.fastlogin.core.shared.FastLoginCore.lambda$load$2(FastLoginCore.java:129) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_292]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.load(FastLoginCore.java:131) ~[?:?]
        at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:88) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordL
```

### Plugin version

Fastlogin Build #1024

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by elmaslarry** [comment]
@games647 could you add Support for 1.18 in FastLogin please? 👯

**Comment by games647** [comment]
Should be fixed in latest build
